[versions]
agp = "9.0.0"
coilComposeVersion = "3.3.0"
glanceAppwidget = "1.1.1"
hiltCompiler = "1.3.0"
hiltCompilerVersion = "2.59.1"
kotlin = "2.3.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockk = "1.14.9"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.4"
composeBom = "2026.02.00"
serialization = "1.10.0"
ktor = "3.4.0"
roomKtxVersion = "2.8.4"
hiltNavigationComposeVersion = "1.3.0"
hiltVersion = "2.59.1"
navigationComposeVersion = "2.9.7"
appcompat = "1.7.1"
material = "1.13.0"
datastore = "1.2.0"
androidxTestCore = "1.7.0"
androidxTestRunner = "1.7.0"
androidxTestRules = "1.7.0"
kotlinx-coroutines = "1.10.2"
turbine = "1.2.1"
orbit = "11.0.0"
firebase-crashlytics-gradle = "3.0.6"
firebase-perf-plugin = "2.0.2"
material3-icons = "1.7.8"
monitor = "1.8.0"
junitKtx = "1.3.0"
lifecycleProcess = "2.10.0"
uiTextGoogleFonts = "1.10.3"
okHttp3Version = "5.3.2"
material3Version = "1.5.0-alpha14"
ksp = "2.3.3"
ktlint = "14.0.1"
detekt = "1.23.8"
jacoco = "0.8.11"
android-quality = "unspecified"
coreSplashScreen = "1.2.0"

[libraries]

# ----------------------------
# ANDROIDX CORE / APP
# -----------------------------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }

# ----------------------------
# COMPOSE
# -----------------------------
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Version" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material3-icons" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashScreen" }

# ----------------------------
# COMPOSE TEST
# -----------------------------
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }


# ----------------------------
# NAVIGATION
# -----------------------------
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }

# ----------------------------
# HILT
# -----------------------------
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
dagger-hilt-agp = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltVersion" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
google-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompilerVersion" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }

# ----------------------------
# ROOM
# -----------------------------
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtxVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtxVersion" }
room-paging = { module = "androidx.room:room-paging", version.ref = "roomKtxVersion" }
androidx-room-testing = { group = "androidx.room", name = "room-testing" }

# ----------------------------
# KTOR / NETWORKING
# -----------------------------
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }

# ----------------------------
# OKHTTP (para Coil)
# -----------------------------
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp3Version" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp3Version" }

# ----------------------------
# KOTLINX (Coroutines / Serialization)
# -----------------------------
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# ----------------------------
# TESTING
# -----------------------------
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }


# ----------------------------
# MVI
# -----------------------------
orbit-core = { group = "org.orbit-mvi", name = "orbit-core", version.ref = "orbit" }
orbit-viewmodel = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "orbit" }
orbit-mvi = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbit" }


# ----------------------------
# MULTIMEDIA (COIL / LOTTIE)
# -----------------------------
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilComposeVersion" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilComposeVersion" }
coil3-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilComposeVersion" }


# ----------------------------
# MATERIAL DESIGN
# -----------------------------
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# ----------------------------
# GRADLE / KOTLIN PLUGINS
# -----------------------------
gradle = "com.android.tools.build:gradle:9.0.0"
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }


[plugins]
# --- Android ---
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp  = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# --- Hilt ---
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
# --- Kotlin Serialization ---
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# ---- KtLint ----
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
# --- Android Conventional Plugin ---
android-quality = { id = "android.quality", version.ref = "android-quality" }
